/**
 * This package contains generated class files meant to model the response coming
 * back from Wunderground. These were generated by <a href="http://jsonschema2pojo.org">jsonschema2pojo.org</a>.
 * They have been stripped down (they were originally generated at over 2,400 LOC!)
 * to just what we need for our purposes. <p />
 * 
 * Don't edit these classes unless responding to changes in Wunderground's JSON. The
 * only class that should ever read from these class is {@link WundergroundResponse} 
 * which has been designed to insulate the outside world from {@link NullPointerException}s
 * resulting in malformed responses.
 */
package vashaina.ha.weather.ext.service.wunderground.response;
